# These are supported funding model platforms

github: [sohaibamjad169]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: sohaibamjad169
custom: https://www.buymeacoffee.com/sohaibamjad169
